### PR TITLE
manual.adoc: add Gentoo Linux installation method

### PR DESCRIPTION
**Pull request by mjkalyan**

### CODE REVIEW

**Comment by lnicola** [comment]
Thanks! Can you please file this against the main RA repo?

**Comment by mjkalyan** [comment]
No problem :)

What's the process for filing it there? Should I link this PR as an issue [here](https://github.com/rust-analyzer/rust-analyzer/issues)?

**Comment by lnicola** [comment]
You don't need to create an issue, just a PR is enough.

**Comment by mjkalyan** [comment]
Done, closing.

**Pull request closed without merging**
