### PR TITLE
Add post content to feed

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by matklad** [comment]
Is the description filed right for this? Like, it sounds like it isn’t, but I admittedly had zero idea about how this whole atom/rss thing works

**Comment by killercup** [comment]
I just copied it from the template I use for my blog where it seems to work

**Comment by killercup** [comment]
psst i just wanted to do this PR again seeing the lastest changelog post

**Comment by matklad** [comment]
Still not sure if this is the right thing to do, but probably won't remember to research this properly once I have time :)

**Comment by killercup** [comment]
fyi, just saw the change log incl all its content in my feed reader, so that's nice :)

**Pull request merged**
